// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE42QFsEJ84hTkjsu6utzHslCEyDXOg_o',
    appId: '1:499143933475:web:3b478bf27a6deb2303fb96',
    messagingSenderId: '499143933475',
    projectId: 'flutter-bootstrap-e405d',
    authDomain: 'flutter-bootstrap-e405d.firebaseapp.com',
    storageBucket: 'flutter-bootstrap-e405d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEWqoMQCp7OtgmWiQdZkLrCAtH_4fbxi4',
    appId: '1:499143933475:android:54ab7382cd2b355403fb96',
    messagingSenderId: '499143933475',
    projectId: 'flutter-bootstrap-e405d',
    storageBucket: 'flutter-bootstrap-e405d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrW9GPH9mFGd4njb2NyBGKtHzBYcaOTfc',
    appId: '1:499143933475:ios:4915027701d82fcf03fb96',
    messagingSenderId: '499143933475',
    projectId: 'flutter-bootstrap-e405d',
    storageBucket: 'flutter-bootstrap-e405d.appspot.com',
    iosBundleId: 'com.raz.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrW9GPH9mFGd4njb2NyBGKtHzBYcaOTfc',
    appId: '1:499143933475:ios:4b4f81c1f586790903fb96',
    messagingSenderId: '499143933475',
    projectId: 'flutter-bootstrap-e405d',
    storageBucket: 'flutter-bootstrap-e405d.appspot.com',
    iosBundleId: 'com.raz.flutterapp.RunnerTests',
  );
}
